/**
 * Created by zachary_edgell on 12/1/21.
 */

global class TaxDataInfo {
    @InvocableVariable
    @AuraEnabled global Integer Period; //200012
    @InvocableVariable
    @AuraEnabled global String Form;    //ANNUAL
    @InvocableVariable
    @AuraEnabled global String UpdateDate;  //06/13/2021
    @InvocableVariable
    @AuraEnabled global String FilingStatus;    //SINGLE
    @InvocableVariable
    @AuraEnabled global String AnnualForm;  //1040
    @InvocableVariable
    @AuraEnabled global Integer AGI;    //2599
    @InvocableVariable
    @AuraEnabled global Integer IRSBalance; //0
    @InvocableVariable
    @AuraEnabled global String FileDate;    //05/07/2001
}